---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-gpu
  namespace: argocd # MUST be argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/charlesthomas/homelab-intel-device-plugins-gpu
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: intel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: deviceplugin.intel.com
      kind: GpuDevicePlugin
      name: intel-gpu-device-plugin
      jsonPointers:
          - /spec/resourceManager
