---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd # MUST be argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/charlesthomas/homelab-reloader
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: reloader-reloader
      jqPathExpressions:
          - .spec.template.spec.containers[0].env[].valueFrom.resourceFieldRef.divisor
